name: rb_photon_prod
channels:
  - forge
  - defaults
  - conda-forge
dependencies:

  - cython=0.29.32
  - jupyter=1.0.0
  - libcblas=3.9.0
  - libclang=12.0.0
  - libcxx=16.0.6
  - matplotlib=3.7.1
  - matplotlib-inline=0.1.6
  - more-itertools=8.12.0
  - numpy=1.25.2
  - notebook=6.5.4
  - pandas=1.5.3
  - pickleshare=0.7.5
  - python=3.10.6
  - python-build=0.10.0
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-installer=0.6.0
  - python-json-logger=2.0.7
  - python_abi=3.10
  - qutip=4.7.2
  - scipy=1.10.1


