name: rb_photon_prod
channels:
  - forge
  - defaults
  - conda-forge
dependencies:
  - aiofiles=22.1.0
  - aiosqlite=0.18.0
  - anyio=3.5.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=2.116
  - blas-devel=3.9.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - cachecontrol=0.12.11
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cleo=2.0.1
  - comm=0.1.2
  - crashtest=0.4.1
  - cryptography=41.0.2
  - cycler=0.11.0
  - cython=0.29.32
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distlib=0.3.6
  - dulwich=0.21.3
  - entrypoints=0.4
  - executing=0.8.3
  - filelock=3.9.0
  - freetype=2.11.0
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - html5lib=1.1
  - icu=68.1
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - ipykernel=6.19.2
  - ipython=8.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - jaraco.classes=3.2.1
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=8.1.0
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=2.5.0
  - jupyter_server_fileid=0.9.0
  - jupyter_server_terminals=0.4.4
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.4
  - jupyterlab=3.6.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.22.0
  - jupyterlab_widgets=3.0.5
  - keyring=23.13.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=12.0.0
  - libedit=3.1.20221030
  - libffi=3.4.4
  - libgfortran5=11.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm12=12.0.0
  - libopenblas=0.3.21
  - libpng=1.6.37
  - libpq=12.15
  - libsodium=1.0.18
  - libsqlite=3.39.4
  - libtiff=4.2.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lockfile=0.12.2
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - more-itertools=8.12.0
  - msgpack-python=1.0.3
  - munkres=1.1.4
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=7.7.3
  - nbconvert-core=7.7.3
  - nbconvert-pandoc=7.7.3
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - nptyping=2.5.0
  - nspr=4.35
  - nss=3.74
  - numexpr=2.8.4
  - numpy-base=1.25.2
  - openblas=0.3.21
  - openssl=3.0.10
  - packaging=23.0
  - pandas=1.5.3
  - pandoc=3.1.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.2.1
  - pkginfo=1.9.6
  - ply=3.11
  - poetry=1.4.0
  - poetry-core=1.5.1
  - poetry-plugin-export=1.3.0
  - pooch=1.4.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyaml=20.4.0
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyproject_hooks=1.0.0
  - pyqt=5.15.7
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.6
  - python-build=0.10.0
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-installer=0.6.0
  - python-json-logger=2.0.7
  - python_abi=3.10
  - pytz=2022.7
  - pyyaml=6.0
  - pyzmq=25.1.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.4.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - qutip=4.7.2
  - rapidfuzz=2.13.7
  - readline=8.2
  - requests=2.29.0
  - requests-toolbelt=0.9.1
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - send2trash=1.8.0
  - setuptools=68.0.0
  - shellingham=1.5.0
  - sip=6.6.2
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.4
  - sqlite=3.39.3
  - stack_data=0.2.0
  - terminado=0.17.1
  - testpath=0.6.0
  - threadpoolctl=2.2.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomlkit=0.11.1
  - tornado=6.2
  - traitlets=5.7.1
  - trove-classifiers=2023.3.9
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - typish=1.9.3
  - tzdata=2023c
  - urllib3=1.26.16
  - virtualenv=20.17.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - widgetsnbextension=4.0.5
  - xattr=0.10.1
  - xz=5.2.10
  - y-py=0.5.9
  - yaml=0.2.5
  - ypy-websocket=0.8.2
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2

